
INSERT INTO municipio(idMunicipio,ciudad)VALUES(001,'Acajete');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(002,'Acatlán');	 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(003,'Acayucan');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(004,'Actopan');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(005,'Acula');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(006,'Acultzingo');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(007,'Camarón de Tejeda');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(008,'Alpatláhuac');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(009,'Alto Lucero de Gutiérrez Barrios');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(010,'Altotonga');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(011,'Alvarado');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(012,'Amatitlán');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(013,'Naranjos Amatlán');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(014,'Amatlán de los Reyes');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(015,'Angel R. Cabada');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(016,'La Antigua');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(017,'Apazapan');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(018,'Aquila');	 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(019,'Astacinga');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(020,'Atlahuilco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(021,'Atoyac');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(022,'Atzacan');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(023,'Atzalan');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(024,'Tlaltetela');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(025,'Ayahualulco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(026,'Banderilla');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(027,'Benito Juárez');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(028,'Boca del Río');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(029,'Calcahualco');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(030,'Camerino Z. Mendoza');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(031,'Carrillo Puerto');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(032,'Catemaco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(033,'Cazones de Herrera');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(034,'Cerro Azul');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(035,'Citlaltépetl');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(036,'Coacoatzintla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(037,'Coahuitlán');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(038,'Coatepec');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(039,'Coatzacoalcos');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(040,'Coatzintla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(041,'Coetzala');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(042,'Colipa');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(043,'Comapa');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(044,'Córdoba');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(045,'Cosamaloapan de Carpio');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(046,'Cosautlán de Carvajal');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(047,'Coscomatepec');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(048,'Cosoleacaque');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(049,'Cotaxtla');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(050,'Coxquihui');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(051,'Coyutla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(052,'Cuichapa');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(053,'Cuitláhuac');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(054,'Chacaltianguis');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(055,'Chalma');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(056,'Chiconamel');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(057,'Chiconquiaco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(058,'Chicontepec');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(059,'Chinameca');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(060,'Chinampa de Gorostiza');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(061,'Las Choapas');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(062,'Chocamán');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(063,'Chontla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(064,'Chumatlán');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(065,'Emiliano Zapata');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(066,'Espinal');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(067,'Filomeno Mata');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(068,'Fortín');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(069,'Gutiérrez Zamora');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(070,'Hidalgotitlán');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(071,'Huatusco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(072,'Huayacocotla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(073,'Hueyapan de Ocampo');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(074,'Huiloapan de Cuauhtémoc');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(075,'Ignacio de la Llave');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(076,'Ilamatlán ');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(077,'Isla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(078,'Ixcatepec');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(079,'Ixhuacán de los Reyes');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(080,'Ixhuatlán del Café');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(081,'Ixhuatlancillo');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(082,'Ixhuatlán del Sureste');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(083,'Ixhuatlán de Madero');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(084,'Ixmatlahuacan');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(085,'Ixtaczoquitlán');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(086,'Jalacingo');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(087,'Xalapa');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(088,'Jalcomulco');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(089,'Jáltipan');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(090,'Jamapa');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(091,'Jesús Carranza');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(092,'Xico');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(093,'Jilotepec');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(094,'Juan Rodríguez Clara');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(095,'Juchique de Ferrer');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(096,'Landero y Coss');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(097,'Lerdo de Tejada');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(098,'Magdalena');	 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(099,'Maltrata');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(100,'Manlio Fabio Altamirano');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(101,'Mariano Escobedo');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(102,'Martínez de la Torre');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(103,'Mecatlán');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(104,'Mecayapan');	 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(105,'Medellín de Bravo');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(106,'Miahuatlán');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(107,'Las Minas');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(108,'Minatitlán');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(109,'Misantla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(110,'Mixtla de Altamirano');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(111,'Moloacán');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(112,'Naolinco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(113,'Naranjal');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(114,'Nautla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(115,'Nogales');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(116,'Oluta');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(117,'Omealca');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(118,'Orizaba');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(119,'Otatitlán');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(120,'Oteapan');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(121,'Ozuluama de Mascareñas');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(122,'Pajapan');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(123,'Pánuco');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(124,'Papantla');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(125,'Paso del Macho');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(126,'Paso de Ovejas');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(127,'La Perla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(128,'Perote');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(129,'Platón Sánchez');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(130,'Playa Vicente');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(131,'poza Rica de Hidalgo');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(132,'Las Vigas de Ramírez');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(133,'Pueblo Viejo');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(134,'Puente Nacional');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(135,'Rafael Delgado');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(136,'Rafael Lucio');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(137,'Los Reyes');	 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(138,'Río Blanco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(139,'Saltabarranca');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(140,'San Andrés Tenejapan');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(141,'San Andrés Tuxtla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(142,'San Juan Evangelista');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(143,'Santiago Tuxtla');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(144,'Sayula de Alemánv');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(145,'Soconusco');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(146,'Sochiapa');	 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(147,'Soledad Atzompa');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(148,'Soledad de Doblado');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(149,'Soteapan');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(150,'Tamalín');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(151,'Tamiahua');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(152,'Tampico Alto');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(153,'Tancoco');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(154,'Tantima');		 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(155,'Tantoyuca');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(156,'Tatatila');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(157,'Castillo de Teayo');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(158,'Tecolutla');		
INSERT INTO municipio(idMunicipio,ciudad)VALUES(159,'Tehuipango');	 	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(160,'Álamo Temapache');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(161,'Tempoal');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(162,'Tenampa');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(163,'Tenochtitlán');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(164,'Teocelo');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(165,'Tepatlaxco');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(166,'Tepetlán');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(167,'Tepetzintla');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(168,'Tequila');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(169,'José Azueta');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(170,'Texcatepec'); 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(171,'Texhuacán'); 	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(172,'Texistepec');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(173,'Tezonapa')	; 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(174,'Tierra Blanca');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(175,'Tihuatlán');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(176,'Tlacojalpan');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(177,'Tlacolulan');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(178,'Tlacotalpan');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(179,'Tlacotepec de Mejía'); 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(180,'Tlachichilco');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(181,'Tlalixcoyan'); 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(182,'Tlalnelhuayocan');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(183,'Tlapacoyan');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(184,'Tlaquilpa');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(185,'Tlilapan')	;
INSERT INTO municipio(idMunicipio,ciudad)VALUES(186,'Tomatlán')	;
INSERT INTO municipio(idMunicipio,ciudad)VALUES(187,'Tonayán');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(188,'Totutla');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(189,'Tuxpan');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(190,'Tuxtilla');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(191,'Ursulo Galván');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(192,'Vega de Alatorre');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(193,'Veracruz') ;
INSERT INTO municipio(idMunicipio,ciudad)VALUES(194,'Villa Aldama');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(195,'Xoxocotla');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(196,'Yanga');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(197,'Yecuatla');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(198,'Zacualpan');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(199,'Zaragoza');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(200,'Zentla');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(201,'Zongolica');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(202,'Zontecomatlán de López y Fuentes');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(203,'Zozocolco de Hidalgo');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(204,'Agua Dulce');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(205,'El Higo')	 ;
INSERT INTO municipio(idMunicipio,ciudad)VALUES(206,'Nanchital de Lázaro Cárdenas del Río');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(207,'Tres Valles');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(208,'Carlos A. Carrillo');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(209,'Tatahuicapan de Juárez');	
INSERT INTO municipio(idMunicipio,ciudad)VALUES(210,'Uxpanapa');	 
INSERT INTO municipio(idMunicipio,ciudad)VALUES(211,'San Rafael');
INSERT INTO municipio(idMunicipio,ciudad)VALUES(212,'Santiago Sochiapan');